wiki_pages = {
    "language": [
        "Mazanderani language",
        "Talysh language",
        "Balochi language",
        "Kurdish language",
        "Pashto",
        "Ossetian language",
        "Zaza language",
        "Luri language",
        "Tat language (Caucasus)",
        "Persian language",
        "Avestan",
        "Middle Persian",
        "Iranian_languages#Old_Iranian",
        'Gilaki language',
    ],

    "language_family": [
        "Iranian languages",
        "Category:Northwestern Iranian languages",
        "Caspian languages",
        "Indo-Iranian languages",
        "Indo-European languages",
        "Proto-Indo-European language",
        "Western Iranian languages",
        "Eastern Iranian languages",
    ],

    "linguistics": [
        "Language family",
        "Dialect continuum",
        "Morphology (linguistics)",
        "Phonology",
        "Syntax",
        "Persian alphabet",
        "Languages of Iran",
        "Languages of the Caucasus",
        "Language contact",
    ],

    "country": [
        "Iran",
        "Afghanistan",
        "Pakistan",
        "Iraq",
        "Turkey",
        "Tajikistan",
        "Azerbaijan",
        "Armenia",
        "Georgia (country)",
        "Russia",
    ],

    "capital_city": [
        "Tehran",
        "Kabul",
        "Islamabad",
        "Baghdad",
        "Ankara",
        "Dushanbe",
        "Baku",
        "Yerevan",
        "Tbilisi",
        "Moscow",
    ],

    "food": [
        "Chelow kabab",
        "Ghormeh sabzi",
        "Aush reshteh",
        "Kabuli palaw",
        "Chapli kebab",
        "Dolma",
        "Baklava",
        "Pilaf#Central_Asia",
        "Khachapuri",
        "Borscht",
    ],

    "irrelevant_general": [
        "Volcano",
        "Photosynthesis",
        "Quantum mechanics",
        "Chess",
        "Basketball",
        "Solar System",
        "Coffee",
        "Piano",
        "Mount Everest",
        "World War II",
        "Shark",
        "Cinema",
        "Bicycle",
        "Honey",
        "Rainforest",
        "Architecture",
        "Chocolate",
        "Computer mouse",
        "Origami",
        "Ocean",
    ],
}